# Generated by Django 6.0.4 on 2026-04-08 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('locked_until', models.DateTimeField()),
                ('locked_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduler_lock',
            },
        ),
        migrations.CreateModel(
            name='ScheduledJobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_key', models.CharField(max_length=255, unique=True)),
                ('job_type', models.CharField(choices=[('refresh_financial_report', 'Refresh Financial Report'), ('refresh_orphan_ebs', 'Refresh Orphan EBS')], db_index=True, max_length=50)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('company_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('scope_type', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('scope_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('project_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('period_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('period_month', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('snapshot_date', models.DateField(blank=True, db_index=True, null=True)),
                ('priority', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=128)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('broker_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduled_job_execution',
                'indexes': [models.Index(fields=['job_type', 'status'], name='idx_job_type_status'), models.Index(fields=['tenant_id', 'job_type'], name='idx_job_tenant_type')],
            },
        ),
    ]
