# Generated by Django 6.0.4 on 2026-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('company_id', models.CharField(db_index=True, max_length=100)),
                ('scope_type', models.CharField(choices=[('client', 'Client'), ('area', 'Area'), ('project', 'Project')], db_index=True, max_length=20)),
                ('scope_id', models.CharField(db_index=True, max_length=100)),
                ('period_year', models.PositiveIntegerField(db_index=True)),
                ('period_month', models.PositiveIntegerField(db_index=True)),
                ('report_type', models.CharField(choices=[('financial_monthly', 'Financial Monthly')], db_index=True, max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('report_payload', models.JSONField(default=dict)),
                ('source_version', models.CharField(blank=True, default='', max_length=100)),
                ('generated_at', models.DateTimeField()),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'financial_report_snapshot',
                'indexes': [models.Index(fields=['tenant_id', 'scope_type', 'scope_id', 'period_year', 'period_month'], name='idx_financial_lookup'), models.Index(fields=['tenant_id', 'company_id', 'period_year', 'period_month'], name='idx_financial_company_period')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'scope_type', 'scope_id', 'period_year', 'period_month', 'report_type', 'is_current'), name='uq_current_financial_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='OrphanEBSSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('company_id', models.CharField(db_index=True, max_length=100)),
                ('project_id', models.CharField(db_index=True, max_length=100)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('volume_id', models.CharField(db_index=True, max_length=100)),
                ('volume_name', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(db_index=True, max_length=50)),
                ('volume_type', models.CharField(blank=True, default='', max_length=50)),
                ('size_gib', models.PositiveIntegerField(default=0)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('ranking_position', models.PositiveIntegerField(db_index=True, default=0)),
                ('details_payload', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'orphan_ebs_snapshot',
                'indexes': [models.Index(fields=['tenant_id', 'company_id', 'project_id', 'snapshot_date'], name='idx_orphan_snapshot_lookup'), models.Index(fields=['tenant_id', 'project_id', 'monthly_cost'], name='idx_orphan_project_cost')],
            },
        ),
    ]
