# Generated by Django 6.0.4 on 2026-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawCostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('company_id', models.CharField(db_index=True, max_length=100)),
                ('area_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('project_id', models.CharField(db_index=True, max_length=100)),
                ('service_name', models.CharField(db_index=True, max_length=100)),
                ('period_year', models.PositiveIntegerField(db_index=True)),
                ('period_month', models.PositiveIntegerField(db_index=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw_cost_record',
                'indexes': [models.Index(fields=['tenant_id', 'company_id', 'period_year', 'period_month'], name='idx_raw_cost_company_period'), models.Index(fields=['tenant_id', 'project_id', 'period_year', 'period_month'], name='idx_raw_cost_project_period'), models.Index(fields=['tenant_id', 'area_id', 'period_year', 'period_month'], name='idx_raw_cost_area_period')],
            },
        ),
    ]
